### PR TITLE
Improved logging

### PR DESCRIPTION
**Pull request by SweVictor**
Completely rewritten logging for js to improve code structure and user experience
- configuration setting for log level
- centralized logging based on `winston`
- color coded logs
- updates readme with log settings and notes on how to export logs

Also breaks out configuration fetching in js, removes the redundant `plejd.json` file and cleans up code from `plejd.sh`.

### CODE REVIEW

**Comment by kodarn** [comment]
Nice work! I have been missing prepended timestamps! :grinning: :+1:

**Comment by SweVictor** [comment]
image

Absolutely!

**Comment by icanos** [comment]
Great work! One small thing though, I'd like the file names to conform to the rest of the project in using lower case names. Nothing major :-)

**Comment by SweVictor** [comment]
I can change it for sure, however the semantics is different. The two new files export the class directly and is used `const Logger = require('./Logger')`, while most other files use `const mqtt = require('./mqtt'); const MqttClient = mqtt.MqttClient;` (or `const MqttClient = require('./mqtt`).MqttClient;`.

I personally prefer the "follow default export naming convention" mentioned for example here [AirBnB style guide](https://github.com/airbnb/javascript#naming--filename-matches-export) and also strive for "one export per file", but I realize it's a bit different than today.

Either way I think it's good to set a pattern. What do you think, how should we proceed? Always export a "wrapper" (`mqtt` above)? Move towards AirBnB style? 

On a side note I am personally like named exports than default exports, so I would normally do similar to how you have done so far (with other syntax) `export class Logger { ...} `  /  `import { Logger } from './Logger;`, which I suppose would work with the above example as well (`const { MqttClient } = require('./mqtt')`). This does not seem to be the NodeJS standard though...

**Comment by icanos** [comment]
I agree with you 100% regarding exports and classes, I like the AirBnB style. Think this addon has grown a bit from my initial tests :-) therefore the structure today is quite poor.

When working with React and such, you normally (at least if you scan the internet a few seconds :-D) use default exports if you don't have more than one export. I can't say that I'm pro this or that, as long as we follow the same standard through out the whole project.

**Comment by SweVictor** [comment]
So - what's the decision :)

I'm quite fine with either way forward, but I think it's good to decide "something".

**Comment by icanos** [comment]
Lets follow the AirBnB style guide and rework any files not conforming to that. That would also mean that we use default exports and strive for a single export per file.

**Comment by SweVictor** [comment]
Adjusted code style on top of this PR, but broke out in separate branch/pr for comparison purposes. Is a bit opinionated and touches a lot of files, feel free to reject or suggest major changes!

**Pull request merged**
