### PR TITLE
Added more documentation to install steps

### PR DESCRIPTION
**Pull request by polyzois**

### CODE REVIEW

**Comment by SweVictor** [comment]
Very nice! I like the concept!

However, I do think that the Details.md file needs to be in the `plejd` directory. The root is a "repository for addons", the `plejd` folder is the root for the actual addon.

You think you could change that and update the reference in the Readme?

Apart from that I think it looks good. I suppose you have good reasons for updating the mqtt part for example 😄

**Comment by SweVictor** [comment]
@polyzois - any thoughts about the comments?

**Comment by SweVictor** [comment]
Alright, despite lack of comment I'll merge this and fix file naming in develop branch

**Comment by polyzois** [comment]
Sorry I really Didn't see this until today :(
I can move the file in a new pull request.
I created the file as a reminder to my future self.



Skickat från min iPad

**Comment by polyzois** [comment]
I just documented what I actually did to get it running

Skickat från min iPad

**Pull request merged**
