### PR TITLE
Integrated current state fetch from plejd mesh

### PR DESCRIPTION
**Pull request by chickenTurtle**
See issue #218

Still need help to update the state of the devices, see plejd/PlejdBLEHandler.js#375.

The reason for many changes is that I ran `npm run lint:fix`

### CODE REVIEW

**Comment by Flole998** [comment]
@icanos Can this be reviewed and merged please?

**Comment by SweVictor** [comment]
I looked through the code quickly. To me, it does not look complete yet. Anyone tested it successfully?

Regarding linting, that's always good, but please keep it in a separate commit if possible to make it easier to decipher what is linting and what are actual changes.

**Comment by Flole998** [comment]
I tested it and at least for me it seems to work.

**Comment by chickenTurtle** [comment]
@SweVictor I have now removed the linting changes. This PR only contains changes regarding the state fetch from plejd mesh

**Pull request closed without merging**
