### PR TITLE
Fix for issue discussed in #198. 

### PR DESCRIPTION
**Pull request by faanskit**
Scene device triggers were not unique from Scenes and device_trigger /config topic was too long

### CODE REVIEW

**Review by SweVictor — APPROVED** [review]
Really very strange that these changes. The `device` part should not have to be unique (it IS the same device), and mqtt topic length also seems strange as a limitation...

But going from not working to working is of course a great step forward!

**Comment by faanskit** [comment]
Yea, agree. 
But empirical tests were conclusive. Guess a few more tests would be needed to fully conclude.
Possibly ask the devs of HA.

**Comment by faanskit** [comment]
> Really very strange that these changes. The device part should not have to be unique (it IS the same device), and mqtt topic length also seems strange as a limitation...

Maybe not super strange. From `homeassistant/components/scene/__init__.py`:
```
class Scene(Entity):   
 """A scene is a group of entities and the states we want them to be."""
```

> With the working solution - can you see the device triggers somewhere in HA?

Yes, see screenshots below. Note "Model" is named Scene by you ;-)


> Do they show up in the Logbook?

Niether in logbook nor in history. See screenshots.


**Device**
enheter
enhetsinformation
enhetsinfo_mqtt

**Entity**
entiteter
entitetsinformation


**History**
history


**Logg**
logg

**Comment by SweVictor** [comment]
With the current develop (without this PR) I can see similar info under MQTT info under the scene which shows up under entities. 

image

I also see the MQTT message come through, but no automation is triggered. Maybe it is as you say that while you can combine sensors and outputs in one device you cant combine scenes and other stuff (device triggers) in one device...

**Review by SweVictor — APPROVED** [review]

**Comment by SweVictor** [comment]
Alright, merging this then. Thanks for the fix!

**Comment by masfak97** [comment]
If I understand it correctly, the 0.8.0-beta should make device triggers work? However, even with the 0.8.0-beta installed I can't get my automation in Home Assistant to trigger repeatedly. 
When the plejd add-on is started, both my scenarios are created and visible in MQTT Explorer as a retained message with QoS 0 even though the payload says QoS 1. The automation gets triggered. 

Every following time the plejd scenario gets called (double click physical switch) the original message fails to be replaced but it seems as if a message goes through on the parent topic (homeassistant/device_automation/plejd/XXXX_trig/ instead of homeassistant/device_automation/plejd/XXXX_trig/config). Sometimes the message is retained but still can't be replaced.

If I delete the entire message in MQTT explorer and then double-click, an empty message is created with topic homeassistant/device_automation/plejd/XXXX_trig/state. After that, for each double-click, the empty message is deleted and created. 

If I restart the plejd add-on, the messages are recreated and the automation triggers once.

Do you have any ideas on what to do? I would really like to be able to trigger HA automations with Plejd scenes.

**Comment by masfak97** [comment]
Found another thread discussing this and will answer my own question. Triggering an automation by an MQTT PLEJD automation trigger in HA isn't done by reacting to the MQTT message, rather using the created device with the same name as the scenario in the PLEJD app as a trigger. This works fine for me.

**Pull request merged**
