### PR TITLE
Improve transitioning of brightness

### LINKED ISSUE #68: Reverse transition: revisit
Hi icanos

I was not able to reopen my previous ticket so I created a new one.

I have upgraded to 0.4.1 and was under the impression that the reverse transition bug was solved in this revision. After some testing I experience the same behavior as described below.

Thanks for taking some time to look into this bug once again, am I doing something wrong here?

The transition to make a light source brighter from lets say 10 to 254 over 20 seconds works fine...

entity_id: light.lounge_tak
brightness: 254
transition: 20
...but going in the other direction from 254 to 10 over 20 seconds results in a direct jump to 10.

entity_id: light.lounge_tak
brightness: 10
transition: 20
Also if the light source is already at brightness 100 and should with transition move to 254 it seems to start at lowest brightness before moving to 254 while the expected behavior would be starting at 100 and move to 254.

I have tested this with an IKEA trådfri light source and that works fine.

Thanks again for your efforts!

-Daniel

### LINKED ISSUE #124: light.turn_off turns the lights on
## To reproduce
- turn on a light with max brightness -> light turns on [OK]
- turn off the same light -> light turns off [OK]
- attempt to turn off the same light with a transition parameter of 10s (transition: 10) -> light turns **on** and subsequently fades out over a period of 10s [NOK]

The expected behavior would be that the light (which was already off) is unaffected by a light.turn_off command. 

## Use case
This negatively affects automations where a trigger snapshots a current light setting and then collectively turns off several lights. In essence, this cannot be performed. Instead, one needs to separately check each light and issue and fade them out individually. 

## System configuration

version | 2020.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v7l
arch | armv7l
timezone | Europe/Stockholm

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.9
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.13
disk_total | 28.0 GB
disk_used | 7.2 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | TellStick (2.0), File editor (5.2.0), Node-RED (7.2.11), Terminal & SSH (8.10.0), deCONZ (6.6.1), Plejd (0.4.8), Mosquitto broker (5.1), SONOS AudioClip TTS (2.0.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | storage
views | 7
resources | 0

</details>

### PR DESCRIPTION
**Pull request by SweVictor**
- Unified turn on/off - brightness = 0 => turn off command
- Cancel any ongoing transition before starting new
- Drop transition steps if communication is slow
- Closes #68 
- Closes #124

### CODE REVIEW

**Comment by icanos** [comment]
Looks nice, will review asap :) thanks!

**Comment by SweVictor** [comment]
Nice! 

Some more testing would not hurt, but seems to work quite well for me at least. 

When transitioning one could discuss how to handle non-dimmable units. Currently they change state instantly, but we could also trigger those at the end of the transition potentially.

**Comment by icanos** [comment]
I would argue that transitions should only be valid and available for dimmable units.

**Comment by f00dagi** [comment]
Release it and I will be happy to test!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SweVictor** [comment]
@icanos True. I'm looking at the "night time" case (entity_id = all, brightness = 0, transition = 60 for example). I did however look at how another integration does things (RFXtrx). They trigger change immediately so seems like the right way to do things.

**Comment by SweVictor** [comment]
A final thing from my side: Transitioning to off will set "last brightness" very low. Default turn-on action is to turn on to last previous value. Is it possible to send a dim value to the Plejd turn_off command? So, basically send {state: 0, dim: 150} similar to how turn_on works?

If so, that would probably be a good idea to implement so that transitioning to off ends with setting {state: 0, dim: initialBrightness}, but that's not something I have tested.

**Comment by icanos** [comment]
Ah, I see. Since it doesn't work as of now, I'd say that would be a great start (doing it like RFXtrx).

**Comment by SweVictor** [comment]
Agreed. Probably a better solution either way to change state directly. If you want something else it's easy to add delays in HA instead.

**Pull request merged**
