### PR TITLE
Feature/readme changelog

### LINKED ISSUE #126: Request: Clarify versions/readme
Versions and README are currently (at least to me) a bit confusing. A changelog or at least a clear version indication would be highly appreciated.

I, using "Easy installation", have the latest (as of 2020-12-31) version installed. Tried `includeRoomsAsLights: true` config setting, but nothing seems to happen (no MQTT messages with "room" type posted). Started reporting that as an issue, but realized I'm not sure what is running and what is the latest version.
* HA says `Plejd - Current version: 0.4.8` (is this maybe taken from plejd/config.json?)
* Readme changelog section shows 0.4.5 as latest
* (Releases show v0.1.4 as latest, presumably releases aren't used anymore)
* plejd/Readme seems to be an old version of Readme, maybe remove? Unfortunately plejd/readme is the one picked up by HA
* `includeRoomAsLights` is said to require v.5. Is that possibly newer than 0.4.8?

After the above investigation, maybe the version in plejd/config.json is enough, but if that is the "real" version it would be great if that would be mentioned in the main readme, and also if there is only one readme in the project to avoid confusion.

Edit: A good way to format a changelog could be this. I could potentially try to help structure this if that would be of interest @icanos  https://keepachangelog.com/en/1.0.0/

Thanks for your great work regarding the addon btw, really really welcome!

### PR DESCRIPTION
**Pull request by SweVictor**
Improve changelog and readme, and prepare for 0.5.0 release

- Closes #126

### CODE REVIEW

**Comment by SweVictor** [comment]
Tags work well for getting some help with changelog information, so please tag 0.5.0 and maybe also last release before that if possible.

This is the "simple" fix for #126, meaning structure is unchanged and readme and changelog have simply been copied to the /plejd directory

**Comment by icanos** [comment]
Looks neat, perfect update to the README and I think it's time for a 0.5.0 release. We'll hold off another day or two before releasing it, allowing some people to test some of the currently open issues.

I'll make sure to tag the current release as well as 0.5.0 and also create a dev branch.

**Comment by SweVictor** [comment]
Updated the readme as discussed above. It's easy to revert if you prefer the earlier structure.

**Comment by icanos** [comment]
Can you update the readme with the changes done in #114? Merge conflict atm, sorry.

**Pull request merged**
