### PR TITLE
Feature/restructure ble

### PR DESCRIPTION
**Pull request by SweVictor**
Separate device management and BLE channel handling. Clean up event subscriptions and clarify emits.

### CODE REVIEW

**Comment by SweVictor** [comment]
So - finally I'm through with my main thoughts on refactoring the code base. One place where state is stored, BLE handling separate, device state management separately.

**Comment by icanos** [comment]
Really great work done here, love the new structure and the separation of BLE comm.

**Comment by SweVictor** [comment]
Thanks! Yeah, I'm thinking this is shaping up nicely too. 

Has been some strange stuff with dbus exhausting internal resources, but sharing that instance seems to solve that. I'm long-term testing this now, but so far it looks promising. 

Other testers are most welcome, I'll probably merge this next week to develop if nothing new comes up.

**Comment by SweVictor** [comment]
So - after a few days working this error surfaced. Emitted from `dbus-next`

```
DBusError: Resource Not Ready
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:337:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:96:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:146:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
```

Seems like the underlying error is `org.bluez.Error.NotReady`, also get the same in `bluetoothctrl`, also after `power off` / `power on`.

Anyone knows this error from before?

I managed to solve it temporarily, not sure what though (without restarting). The only command i run (in root console) were (in order)
* `btmoon` (which i think did nothing)
* `bluez-simple-agent` (which crashed with a trace `import 'dbus'` => `no module named dbus`
* `bluetoothctl` (which now as compared to before shows `Agent registered` before listing the command console)

The error came back after a while, and also persisted addon restart. Power off => wait for a slightly longer time (20+ seconds) seemed to fix it the second time.


Any ideas?

**Comment by SweVictor** [comment]
So. I have in my installation had TONS of disconnects due to a (for now somewhat intentionally) bad placed BLE dongle. I have moved it to a better place now and have no disconnects (and therefore no issues). So - I'll merge this now and might break out the BLE discussion to a separate issue.

**Pull request merged**
