### PR TITLE
Fix Add-on store problems

### PR DESCRIPTION
**Pull request by magicus**
Converting the `config.json` to `config.yaml` seems to be the first step towards resolving #256. There seems to be additional hurdles, though.

### CODE REVIEW

**Comment by magicus** [comment]
Ok, this patch more or less works now (as far as I can tell; it installed the Add-on on my system). There is one problem that I did not know how to best resolve, though. For logging purposes, the information from `config.json` were read into an `AddonInfo` object in `Configuration.js`. 

But now the file is in YAML format, so the `JSON.parse()` method will not handle it. (I presume)

I have some ideas on how to resolve this, none is ideal so I'd like feedback, and/or that @icanos takes over this PR and fixes this part.

1) Keep a copy of the info in config.json as well
2) Keep the format in pure json even if the file is named `config.yaml` (this is legal but not recommended)
3) Skip the logging and remove this code
4) Add a yaml parser, like `js-yaml` to the installation (this is the preferred option I think)

**Comment by e120guru** [comment]
Has there been any more progress on this to get it to show up in the Addon Store?

**Comment by e120guru** [comment]
Ok, after a reboot or two it all of a sudden showed up

**Comment by SweVictor** [comment]
@e120guru @magicus - so... It IS showing up without the need for the requested change in the linked PR?

**Comment by magicus** [comment]
I honestly don't remember if I managed to get it working without this patch, or if I am still running a patched version on my hass installation, based on my personal repo. But if other users get it to work without the patch, I guess it is not needed.

**Pull request closed without merging**
