### PR TITLE
Feature/code style

### PR DESCRIPTION
**Pull request by SweVictor**
Adjust code to airbnb style guid, including eslint rules and prettier config.

Relates to PR #149

### CODE REVIEW

**Comment by SweVictor** [comment]
Forgot to link - diff for code style changes are here
https://github.com/SweVictor/hassio-plejd/compare/feature/improved-logging...SweVictor:feature/code-style

**Comment by icanos** [comment]
Really like the updated code style, this is how it should have looked from the start. Great work!

**Comment by SweVictor** [comment]
> Really like the updated code style, this is how it should have looked from the start. Great work!

Great to hear! Thought it would be good to do a first pass over the code at least. And well - it's always a bit different when coding only by yourself regarding code style. This is overall a quite minor change, really appreciate the hard work you have been putting in to make the Plejd system work in HA (which is still the main thing here!).

**Comment by SweVictor** [comment]
Now code has been updated to actually build/run as well (Dockerfile updated for new file names). Should work the same as earlier code.

**Comment by icanos** [comment]
Maybe we should update the version code as well? Those changes done over the last few weeks should probably stabilize the addon for many of our users. What do you think?

**Comment by SweVictor** [comment]
Sure. I'm not really sure how versioning is done here so I haven't touched that :-)

I also wonder a bit - how should we test things? "Beta" branch (or "vNext")? Or maybe release branch separate from master? Is it possible for end users (in the supervisor UI) to downgrade, select specific versions, or to install a dev branch? I'm not sure how those parts works, but I would prefer than someone apart from me tests new things before release if possible...

Also pending is to at least sync the two readme files so users see the most recent readme in HA, I can probably do that if we think the current structure with double readme's is the best way (I've been thinking about linking the root readme to the inner one that is seen by HA, but I'm not sure exactly what is the best way).

**Comment by icanos** [comment]
I agree with you regarding the README's. We need to sync those and I think we should move the changelog to a separate file too.

I'm not aware of any possibilities to select a version of an addon in the Supervisor UI, so I guess that it's always gonna be the latest version when updating. A separate branch for development is the way I've been working previously and then just made a pull request to the master branch when a new version was ready to be tested. I solved the testing by manually uploading the files to a local repository in Hass.io (copy/paste files into a folder).

I think we merge these changes and test them, if all is ok, we then update the version so that everyone using the addon gets a notification. After that, we create a separate new branch for development work and continues there.

Sounds ok?

**Comment by SweVictor** [comment]
Sounds good. Let's merge this if you agree and people that want can start testing. I can probably fix the readme later today in a separate PR, and then we can break off a dev branch or something like it.

**Pull request merged**
