### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by thomasloven**
Hi!

I have forked this project to create a version that does not rely on the Home Assistant supervisor, but can be run in a standalone docker container. https://github.com/thomasloven/plejd2mqtt

In doing that I've made a few minor tweaks, which I would like to push upstream.

This is the first of those.

Those two files seem to be entirely unused.

### CODE REVIEW

**Comment by SweVictor** [comment]
I think this would be a good thing. 

For me, trying to get things to work in a Windows install, having the `ble.js` still there made it possible for me to with reasonable effort get things working under Windows (dbus-next is not Windows compatible, noble is), so for that special case it was nice the old code was there. `ble.js` is however quite old (pre 0.3), meaning it did not match the newer `ble.bluez.js` and therefore did not work initially with `main.js`. 

Either way I think removing is the right way to go, especially for this repo. If you're interested @thomasloven in your standalone version supporting a Windows installation I could send you my updated `ble.js` that actually works with the new code base. Does not have all the features/resiliency of `ble.bluez.js` but it does work under Windows.

**Comment by SweVictor** [comment]
Btw - Dockerfile needs to be updated to remove the COPY ble.js row

**Comment by icanos** [comment]
Will you update the PR with the changes needed in the Dockerfile too?

**Comment by icanos** [comment]
Thanks :-)

**Pull request merged**
