### PR TITLE
Release 0.10.0

### PR DESCRIPTION
**Pull request by SweVictor**
This is a preparation for release 0.10.0.

The main new feature is support for new devices including LED-75 and SPR-01

Issues solved include
https://github.com/icanos/hassio-plejd/issues/250
https://github.com/icanos/hassio-plejd/issues/232

The device type handling has also been rewritten to avoid crashing the entire addon when an unsupported device is encountered.

**Please** do a manual install of the code in the https://github.com/icanos/hassio-plejd/tree/develop branch to verify this is working before full release.

Intended to be released in a couple of days.

### CODE REVIEW

**Comment by tomjaimz** [comment]
Hi there!  Will this fix also address https://github.com/icanos/hassio-plejd/issues/218?

**Comment by SweVictor** [comment]
@tomjaimz: It does not. It seems like the consensus in tickets related to startup issues is that the best would be to trust the Plejd mesh state rather than the wanted state in HA/MQTT. I'll elaborate a bit in #218.

**Comment by timjackson** [comment]
plejd/CHANGELOG.md needs an update

**Comment by timjackson** [comment]
The copyright year in /README.md needs updating (it should be in sync with plejd/README.md, or perhaps one place is enough?) I think you should also give yourself credit @SweVictor (in both README.md and plejd/README.md, or the consolidated location)

**Comment by timjackson** [comment]
Wouldn't it be a good idea to at least do the "quick fix" for #279 (setting entity names to null) before making this a new release, since that's showing up as a big warning for everyone, and HA is already itself setting them to null as a workaround?

**Comment by SweVictor** [comment]
> Wouldn't it be a good idea to at least do the "quick fix" for https://github.com/icanos/hassio-plejd/issues/279 (setting entity names to null) before making this a new release,

I prefer (in general) to make one change at a time, but given the "set to null" strategy is the right one and does not break stuff, I agree the fix itself is simple...

**Comment by SweVictor** [comment]
> > Wouldn't it be a good idea to at least do the "quick fix" for #279 (setting entity names to null) before making this a new release,
> 
> I prefer (in general) to make one change at a time, but given the "set to null" strategy is the right one and does not break stuff, I agree the fix itself is simple...

@timjackson: As a middle way, I added a quick fix to the "set entity name = null" in a separate branch https://github.com/icanos/hassio-plejd/tree/feature/set-device-name-null

Feel free to test that version for 0.10.0 + the entity name null fix. I have only sanity checked very quickly that fix though.

**Comment by SweVictor** [comment]
This release is now out and available in the public addon channel

**Pull request merged**
