### PR TITLE
MQTT startup bugfix

### PR DESCRIPTION
**Pull request by pierrei**
I got this [issue](https://github.com/icanos/hassio-plejd/issues/218) myself where lights would automatically would turn on when HA restarted.

It seems like the problem is that when the MQTT client is set up it's directly hooked up to listen to updates from MQTT even before we do the HA "discovery". The discovery sends things to MQTT and it seems to trigger the unwanted update where we will receive state changes on lights when they actually didn't change at all.

There are many ways to fix this problem but I figured it would be easiest to just ignore any incoming messages from MQTT while the discovery is running.

I tried this at home and before this fix I had the bug described in the issue:
1. Turning on a light in HA
2. Restarting the Plejd add-on
3. Turning off the light with the Plejd app
4. When the Plejd add-on starts up it turns on the light

With this fix the light no longer comes on.

### CODE REVIEW

**Comment by pierrei** [comment]
I'm actually having some issues with this fix so I'm investigating. The bug is no longer there since it seems it cannot connect to MQTT at all now for some reason 😆

**Comment by pierrei** [comment]
The client ID fix that I tried first didn't actually fix the problem. Investigated some more and figured out the problem is because we're listening to MQTT messages when the discovery is running that's pushing stuff to MQTT. PR updated to fix this instead and PR description and title was updated too.

**Comment by timjackson** [comment]
Is this a competing fix for pull #260 ? Or are they addressing different aspects of the same problem?

**Comment by pierrei** [comment]
@timjackson I had a look and it seems they're not conflicting changes but might solve the same issue but from two different angles. I'd ask the owner/creator of this project to chime in on this and make a call, but unfortunately it seems like he's not very active. I'm running this branch on my own Home Assistant and it's working great, so if you ask me we should merge this one! :)

**Comment by SweVictor** [comment]
Closing this since #297 is in the develop branch. Please test that and we'll reopen this if it's still needed

**Pull request closed without merging**
